// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	shortener "github.com/magmel48/go-web/internal/daemons"
	userlinks "github.com/magmel48/go-web/internal/db/userlinks"
	mock "github.com/stretchr/testify/mock"
)

// Daemon is an autogenerated mock type for the Daemon type
type Daemon struct {
	mock.Mock
}

// EnqueueJob provides a mock function with given fields: item
func (_m *Daemon) EnqueueJob(item shortener.QueryItem) {
	_m.Called(item)
}

// Run provides a mock function with given fields: userLinksRepository
func (_m *Daemon) Run(userLinksRepository userlinks.Repository) {
	_m.Called(userLinksRepository)
}
