// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	daemons "github.com/magmel48/go-web/internal/daemons"
	mock "github.com/stretchr/testify/mock"
)

// Daemon is an autogenerated mock type for the Daemon type
type Daemon struct {
	mock.Mock
}

// EnqueueJob provides a mock function with given fields: item
func (_m *Daemon) EnqueueJob(item daemons.QueryItem) {
	_m.Called(item)
}

// Run provides a mock function with given fields:
func (_m *Daemon) Run() {
	_m.Called()
}
