// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Backup is an autogenerated mock type for the Backup type
type Backup struct {
	mock.Mock
}

// Append provides a mock function with given fields: line
func (_m *Backup) Append(line string) error {
	ret := _m.Called(line)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(line)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadAll provides a mock function with given fields:
func (_m *Backup) ReadAll() map[string]string {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}
